### ISSUE TITLE
요청 인증 페이지에 보충 설명이 필요합니다.

### ISSUE THREAD

**Issue by kijin** [nurigo/sms-api-v3#2]
@bjrambo 님의 소개로 API v3 매뉴얼을 보게 되었습니다. 첫 부분인 "요청 인증" 페이지를 읽다가 사용 방법이 분명하지 않거나 참고소스 내에서 일관성이 없어 보이는 부분을 몇 군데 찾아 알려드립니다.

1. Salt에 포함될 수 있는 문자 종류를 제한할 필요가 있습니다. 특수문자를 넣거나 특수문자를 `%00` 인코딩하여 넣을 수도 있으니까요. 거기에 특수문자를 왜 넣나 하시겠지만 프로그래밍 언어에 따라 난수 생성 방식이 다르고, 여기에 `base64` 등 일반적인 인코딩을 사용하면 본의 아니게 특수문자가 들어가기도 합니다. 그러면 특수문자 때문에 필드 구분에 오류가 발생하거나, `%00` 인코딩 때문에 64바이트가 70바이트로 늘어나는 등 여러 가지 문제가 발생할 수 있습니다. 알파벳 대소문자와 숫자만 사용할 수 있다고 분명히 표기해 주시면 도움이 되겠습니다.
2. Request Syntax에는 날짜 필드명을 `date`라고 정의하고 있으나 그 아래의 자세한 설명에서는 `DateTime`이라고 표기하고 있습니다. 그 밖에도 각 필드의 대소문자가 모두 다릅니다.
3. Signature 생성 예제 코드에서 ISO 8601이 아니라 `date('Y-m-d H:i:s')` 포맷의 날짜를 사용하고 있습니다. ISO 8601에 맞는 `date('c')` 포맷을 사용해야 합니다. 또한 Signature를 생성할 때는 앞서 사용한 `date` (또는 `DateTime`) 필드와 동일한 포맷의 동일한 시간을 사용해야 한다고 명시하는 것이 좋겠습니다. 조금이라도 다르면 HMAC을 비교하는 것 자체가 무의미하지요...
4. Signature 생성 예제 코드에서는 PHP의 `hash_hmac()` 함수를 사용하고 있는데, 이 함수의 결과는 소문자로 나옵니다.  그러나 맨 밑의 Sample Syntax에서는 Signature가 대문자로 나옵니다. 매뉴얼의 다른 예제들은 또 소문자로 나옵니다. 한 쪽으로 통일해 주시면 감사하겠습니다.

API v3는 아직 개발중이신 것으로 알고 있습니다. 개발중인 API와 작성중인 매뉴얼에 오류가 있을 수도 있죠 뭐... 비판이 아니라 더 좋은 API가 나오기를 바라는 마음에서 드리는 말씀이니 이렇게 불쑥 이슈를 등록하는 무례함을 용서해 주시기 바랍니다.

아무쪼록 간결하고 안정적이고 잘 설명된 API를 만들어 주셔서 PHP나 XE뿐 아니라 어떤 언어의 어떤 프레임워크로 만들어진 어떤 어플리케이션에서도 쉽게 연동할 수 있는 SMS 발송 서비스가 되면 좋겠습니다.

**Comment by wileyday** [comment]
관심가져 주시고 구체적인 피드백까지 주셔서 감사합니다 ^^
