### ISSUE TITLE
그룹 리스트 가져오는 반환데이터가 문서와 맞지 않습니다.

### ISSUE THREAD

**Issue by bjrambo** [nurigo/sms-api-v3#3]
http://sms-api-v3.readthedocs.io/ko/latest/GroupMessage/getGroupList.html
문서에서 소개된것과 같이 문서가 반환되는 값이 맞지 않는것 같습니다.
원래는 

$request->groupList->array( groupId => 'GROUPID01');
이렇게 나타나는 것이 이상적이나,
$request->groupList->GROUPID01 (변수명에 그룹아이디가 들어가게되어있네요.)

이 부분을 문서와 동일하게 해야할것 같고.. 만약 문서랑 다르게 한 계획이 맞았던 거라면.. 이방법은 좀 더 생각해보셔야 할것 같아요.

그룹아이디를 모르는 과정에서 변수명으로 선언된것을 실제로 코드로 입력해야하는 부분이 생기는게 아닌가 싶습니다.. 

한번 검토해주세요 :) 

추가적으로 알림톡ATA전송시에 버튼 URL기능이 들어간 알림톡의 경우는 전송이 되고 잇지 않은것을 확인했습니다.

이부분 정상적으로 작동하는건지 검토한번 해주세요 ㅠㅠ..

**Comment by wileyday** [comment]
$response->groupList->GROUPID01 = { ... } 식의 표현이 맞습니다. 문서에서도 Map(Object) 형식으로 기술되어 있고 리턴되는 값도 Map(Object) 형식으로 되어 있습니다.
이렇게 하는 이유는 프로그램에서 그룹ID로 접근하기 용이하기 때문입니다. Array 로 리턴되는 경우 특정 그룹ID로 접근하려면 Loop를 한번 돌면서 그룹ID를 비교해야 하기 때문입니다.

알림톡 버튼 전송의 경우 Backend 서버에 로그를 남기고 있지 않아서 오늘 다시 한번 시도해 주시면 확인해 보겠습니다.
